// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDosf6-TEsnY2FAjs-h6Q3gi84jzqVQOBY',
    appId: '1:1051685805022:web:8806c21ba27f16d8895b4f',
    messagingSenderId: '1051685805022',
    projectId: 'todu-90201',
    authDomain: 'todu-90201.firebaseapp.com',
    storageBucket: 'todu-90201.firebasestorage.app',
    measurementId: 'G-5H446FNCQG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2CCvqnJHCglKhvB0jRS94KQLeTFVr6XM',
    appId: '1:1051685805022:android:8e7142d1f09e34d2895b4f',
    messagingSenderId: '1051685805022',
    projectId: 'todu-90201',
    storageBucket: 'todu-90201.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXjz8d6Jm_3rZECIwqwY6SmLq54uX57Wc',
    appId: '1:1051685805022:ios:5ec1865154cc8e72895b4f',
    messagingSenderId: '1051685805022',
    projectId: 'todu-90201',
    storageBucket: 'todu-90201.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXjz8d6Jm_3rZECIwqwY6SmLq54uX57Wc',
    appId: '1:1051685805022:ios:5ec1865154cc8e72895b4f',
    messagingSenderId: '1051685805022',
    projectId: 'todu-90201',
    storageBucket: 'todu-90201.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDosf6-TEsnY2FAjs-h6Q3gi84jzqVQOBY',
    appId: '1:1051685805022:web:788a3bb0112b6dea895b4f',
    messagingSenderId: '1051685805022',
    projectId: 'todu-90201',
    authDomain: 'todu-90201.firebaseapp.com',
    storageBucket: 'todu-90201.firebasestorage.app',
    measurementId: 'G-SSVPXHF254',
  );
}
